apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bolt-workflow-creator
subjects:
  - kind: ServiceAccount
    name: bolt-workflow-creator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: bolt-workflow-creator
  apiGroup: rbac.authorization.k8s.io
